"""Package a deliberately small, technically screened R04 runtime subset.

No generator, model, source-script execution or subjective listening claim.
Source WAVs are retained; PCM16 quantization is the only derivative operation.
"""
from pathlib import Path
import json
from intake_sfx_r04 import ROOT, INTAKE, QA, EXPECTED, read_audio, write_audio, sha

BANK = INTAKE / 'SABLE_CIRCUIT_SFX_R04_COLOSSAL'
OUT = ROOT / 'assets/audio/combat_r04'
# R05 (2026-09-24): every authored variant for short roles, the previously
# unused hurt / armour-break / ricochet / shield / reload roles, and the cue
# map's own runtime hints (pitch range, per-emitter cooldown, world-position
# spatialisation). Boss blasts keep two long stereo variants for pack size.
# (variants, gain_db, priority, pitch_range, cooldown_ms, spatial, reason)
ALL = [1, 2, 3, 4]
SELECT = {
    'aster_fire': (ALL, -6, 50, [0.97, 1.03], 40, True, 'Precision coil rifle; four variants break repetition.'),
    'rook_fire': (ALL, -5, 55, [0.97, 1.03], 60, True, 'Heavy breach shotgun body.'),
    'mica_fire': (ALL, -6, 50, [0.97, 1.03], 35, True, 'Short PDW, brighter than ROOK.'),
    'enemy_fire': (ALL, -9, 30, [0.95, 1.05], 55, True, 'Hostile machine rifle, under player weapons.'),
    'turret_fire': (ALL, -8, 35, [0.96, 1.04], 100, True, 'Heavy mechanical hostile shot.'),
    'impact_steel_light': (ALL, -10, 40, [0.95, 1.05], 45, True, 'Coil rounds striking robot plating.'),
    'impact_steel_heavy': (ALL, -9, 45, [0.95, 1.05], 50, True, 'Breach pellets striking heavy armour.'),
    'robot_hit': (ALL, -10, 40, [0.95, 1.05], 60, True, 'Electrical/mechanical damage layer.'),
    'impact_concrete': (ALL, -12, 25, [0.94, 1.06], 50, True, 'Rounds absorbed by cover.'),
    'ricochet': (ALL, -14, 20, [0.92, 1.08], 100, True, 'Occasional glancing ricochet off cover.'),
    'shield_hit': (ALL, -9, 60, [0.96, 1.04], 80, True, 'BULWARK front armour deflecting a round.'),
    'shield_break': (ALL, -5, 88, [0.98, 1.02], 220, True, 'Boss shield guard breaking.'),
    'armor_break': (ALL, -5, 80, [0.96, 1.04], 120, True, 'Normal robot destroyed.'),
    'impact_body': (ALL, -8, 70, [0.96, 1.04], 55, True, 'Operator struck: suit impact layer.'),
    'aster_hurt': (ALL, -7, 85, [0.98, 1.02], 110, True, 'ASTER hurt.'),
    'rook_hurt': (ALL, -7, 85, [0.98, 1.02], 110, True, 'ROOK hurt.'),
    'mica_hurt': (ALL, -7, 85, [0.98, 1.02], 110, True, 'MICA hurt.'),
    'aster_reload': (ALL, -12, 45, [0.99, 1.01], 180, True, 'ASTER magazine change.'),
    'rook_reload': (ALL, -12, 45, [0.99, 1.01], 180, True, 'ROOK shell load.'),
    'mica_reload': (ALL, -12, 45, [0.99, 1.01], 180, True, 'MICA magazine change.'),
    'boss_core_hit': (ALL, -12, 60, [0.97, 1.03], 100, True, 'Boss core struck.'),
    'boss_charge': (ALL, -8, 92, [1.0, 1.0], 500, True, 'Boss attack wind-up.'),
    'boss_cross_beam': ([1, 3], -7, 90, [1.0, 1.0], 300, False, 'Full 6.4-second stereo blast; source tails preserved.'),
    'boss_stomp': ([1, 3], -9, 85, [1.0, 1.0], 220, False, 'Full 4-second stereo pressure impact for ground warning detonation.'),
    'boss_destroy': ([2, 4], -6, 100, [1.0, 1.0], 1200, False, 'Full 7-second stereo collapse, only at the death boundary.'),
}
CREDITS = '''SABLE CIRCUIT — SOUND CREDITS

Explosion effects adapted from "2 High Quality Explosions" (track "explode")
by Michel Baradari. Creative Commons Attribution 3.0 Unported (CC BY 3.0).
Original: https://opengameart.org/content/2-high-quality-explosions
License: https://creativecommons.org/licenses/by/3.0/
Modified for SABLE CIRCUIT R04: layering, playback-rate design, equalization,
tail crossfades, stereo diffusion, fades and gain staging; runtime PCM16 export.
No endorsement by the original author is implied.

CC0 sources: The Free Firearm Sound Library — Ben Jaszczak, Brian Nelson,
Kevin Heras, Matthew Nanney.
https://opengameart.org/content/the-free-firearm-sound-library
100 CC0 Metal and Wood SFX — rubberduck.
https://opengameart.org/content/100-cc0-metal-and-wood-sfx
Source conversion mirror: DeathByDenim / openspades-free-pak
https://github.com/DeathByDenim/openspades-free-pak
'''


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    pcm_dir = QA/'selected_pcm16'
    pcm_dir.mkdir(parents=True, exist_ok=True)
    analysis = json.loads((QA/'source_audio_analysis.json').read_text('utf-8'))
    metrics = {r['file'].replace('\\', '/'): r for r in analysis['records']}
    cues = {c['id']: c for c in json.loads((BANK/'CUE_MAP.json').read_text('utf-8-sig'))['cues']}
    rows, gd = [], ['# Generated by tools/audio/build_combat_sfx_bank.py; do not hand edit.', 'extends RefCounted', 'const CUES := {']
    for cue, (variants, gain, priority, pitch, cooldown, spatial, reason) in SELECT.items():
        streams = []
        for number in variants:
            source = BANK / cues[cue]['variants'][number-1]
            if cue in ['boss_cross_beam', 'boss_stomp', 'boss_destroy']:
                source = BANK/'extras/stereo_boss'/source.name
            relative = source.relative_to(BANK).as_posix()
            assert metrics[relative]['technical_ok']
            pcm, rate = read_audio(source)
            destination = pcm_dir/f'{cue}_v{number:02}.wav'
            write_audio(destination, pcm, rate)
            packed = OUT/(destination.stem+'.res')
            streams.append(f'preload("res://assets/audio/combat_r04/{packed.name}")')
            rows.append({'cue': cue, 'source': source.relative_to(ROOT).as_posix(),
                         'source_sha256': sha(source), 'runtime': packed.relative_to(ROOT).as_posix(),
                         'sha256': sha(packed) if packed.exists() else None,
                         'pcm_intermediate': destination.relative_to(ROOT).as_posix(), 'pcm_sha256': sha(destination),
                         'duration_s': len(pcm)/rate, 'channels': pcm.shape[1],
                         'rate': rate, 'bits': 16, 'gain_db': gain, 'priority': priority, 'pitch_range': pitch,
                         'cooldown_ms': cooldown, 'spatial': spatial, 'selection_reason': reason})
        gd.append(f'    "{cue}": {{"streams": [{", ".join(streams)}], "gain_db": {float(gain)}, "priority": {priority}, '
                  f'"pitch": [{pitch[0]}, {pitch[1]}], "cooldown_ms": {cooldown}, "spatial": {str(spatial).lower()}}},')
    gd.extend(['}', 'const CREDITS := '+json.dumps(CREDITS, ensure_ascii=False), ''])
    # Preload serialized WAV resources for export inclusion without a whole-repo import.
    (OUT/'bank.gd').write_text('\n'.join(gd), encoding='utf-8')
    (OUT/'CREDITS.txt').write_text(CREDITS, encoding='utf-8')
    report = {'schema': 1, 'archive_sha256': EXPECTED, 'selected_count': len(rows), 'cues': rows,
              'selection_scope': 'Technical integrity and event-role/spectral screening, not human listening approval.',
              'auditory_review': 'Not claimed: agent audio input is unsupported. Audition reels retained.',
              'excluded': 'Footsteps, melee, dry fire, casing drops, two boss stereo variants, old previews and generation tools remain source-only.',
              'conversion': '48 kHz unchanged; 24-bit to 16-bit PCM only. No normalization, crop or tail truncation. Runtime applies the cue map pitch/gain variation and world-position panning.',
              'license_verified_in_app_browser': ['https://opengameart.org/content/2-high-quality-explosions',
                  'https://opengameart.org/content/the-free-firearm-sound-library',
                  'https://opengameart.org/content/100-cc0-metal-and-wood-sfx',
                  'https://creativecommons.org/licenses/by/3.0/'],
              'license_evidence': {'source_manifest_sha256': sha(BANK/'sources/SOURCE_MANIFEST.json'),
                  'required_credits_sha256': sha(BANK/'CREDITS_REQUIRED.txt'),
                  'runtime_credits_sha256': sha(OUT/'CREDITS.txt'), 'date': '2026-09-19'}}
    (QA/'selected_bank_manifest.json').write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding='utf-8')
    print(json.dumps({'selected':len(rows), 'runtime_bytes':sum((ROOT/r['runtime']).stat().st_size for r in rows if (ROOT/r['runtime']).exists())}))


if __name__ == '__main__':
    main()
